# Generated by Django 4.2.28 on 2026-03-17 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0123_issueworklog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issueworklog',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted At'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='calendar_system',
            field=models.CharField(choices=[('gregorian', 'Gregorian'), ('jalali', 'Jalali')], default='jalali', max_length=20),
        ),
        migrations.CreateModel(
            name='ModuleLabel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_module', to='db.label')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_module', to='db.module')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Module Label',
                'verbose_name_plural': 'Module Labels',
                'db_table': 'module_labels',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='modulelabel',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('module', 'label'), name='module_label_unique_module_label_when_deleted_at_null'),
        ),
        migrations.AlterUniqueTogether(
            name='modulelabel',
            unique_together={('module', 'label', 'deleted_at')},
        ),
    ]
